* Exported from Matlab using EasySpin, 17-Dec-2018 12:33:47
#DESC	1.2 * DESCRIPTOR INFORMATION ***********************
DSRC	MAN
BSEQ	BIG
IKKF	REAL
IRFMT	D
XFMT	D
XTYP	IGD
YTYP	NODATA
ZTYP	NODATA
XPTS	4000
XMIN	0
XWID	3184
TITL	'NUSgrid_PRODEL_example'
*
************************************************************
*
#SPL	1.2 * STANDARD PARAMETER LAYER
OPER	
DATE	17/12/18
TIME	12:33:47
CMNT	
SAMP	
SFOR	
